### PR TITLE
Generate ksonnet.beta.4 based on Kubernetes 1.14

### PR DESCRIPTION
**Pull request by metalmatze**
I've generated ksonnet.beta.4 based on Kubernetes 1.14 swagger.json that I've found through `localhost:8001/openapi/v2`.

I'm not entirely sure if there are other changes necessary to this repository, but this should be the first step.

/cc @bryanl @brancz @tomwilkie

### CODE REVIEW

**Comment by brancz** [comment]
Any chance we can try this out on our code base before merging?

**Comment by metalmatze** [comment]
I'm already on it, converting our kube-prometheus stack with an intermediate dependency to test it.

**Comment by metalmatze** [comment]
Hey @bryanl, do you have any feedback on this? Happy to change this if necessary.

**Comment by Quentin-M** [comment]
How did you generate this without modifying https://github.com/ksonnet/ksonnet-lib/blob/10dc23a02ae2f12c6bb5b85cd51e1bac329b8463/ksonnet-gen/kubeversion/data.go?

**Comment by jwhitcraft** [comment]
@metalmatze did you see this question, I'm still trying to maintain a fork of this as we use this heavily internally and i'm unable to generate ones based on 1.16.x.

Can you provide help on how you did this, if you remember?

**Comment by metalmatze** [comment]
@sh0rez and I maintain a fork that also has newer versions generated:
https://github.com/kube-jsonnet/k

**Pull request merged**
