### PR TITLE
add guestbook example

### PR DESCRIPTION
**Pull request by ngtuna**
The example contains guestbook rc & svc, redis-master/slave rc & svc

### CODE REVIEW

**Comment by hausdorff** [comment]
On phone but you might be interested in some of the examples we're starting to flesh out: https://github.com/ksonnet/ksonnet-lib/tree/sigapps/ksonnet.beta.2

**Comment by hausdorff** [comment]
Ok, so, I'm thinking that probably we will want to not add more examples of `beta.1` since we'd like to deprecate it in favor of `beta.2`. What are your thoughts on this?

**Comment by ngtuna** [comment]
@hausdorff yes thanks I will try the `beta.2` with guestbook and give you feedback

**Comment by bryanl** [comment]
closing due to inactivity

**Pull request closed without merging**
